apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: jupyter-local