apiVersion: v1
kind: ConfigMap
metadata:
  name: localstack-init
data:
  create-bucket.sh: |
    #!/bin/bash -e
    awslocal s3 mb s3://bucket
---
apiVersion: v1
kind: Service
metadata:
  name: localstack-aws
spec:
  ports:
  - name: localstack
    port: 33000
    protocol: TCP
    targetPort: 4566
  selector:
    app: localstack
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  labels:
    app: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
      - env:
        - name: SERVICES
          value: s3
        - name: PORT_WEB_UI
          value: "8080"
        - name: INIT_SCRIPTS_PATH
          value: /init
        image: localstack/localstack:0.12.4
        imagePullPolicy: IfNotPresent
        name: localstack
        ports:
        - containerPort: 4566
          protocol: TCP
        - containerPort: 4571
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /init
          name: localstack-scripts
      restartPolicy: Always
      volumes:
        - name: localstack-scripts
          configMap:
            name: localstack-init
            defaultMode: 0755